# Generated by Django 3.1.6 on 2021-02-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinfoapp', '0003_auto_20210222_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='area',
            new_name='Affected_Area',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='gender',
            new_name='Gender',
        ),
    ]
