# Generated by Django 3.1.6 on 2021-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinfoapp', '0004_auto_20210222_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
